import React from 'react';
import {useCurrentFrame} from 'remotion';
import {COLORS,FONT,alpha,fadeIn} from '../theme';
import type {SceneDef} from '../Video';
import {distillationState} from '../mechanisms/edge10-distillation-state';
const T={title:'Teach a smaller model',classes:['Cat','Dog','Bird'],fixed:'Teacher stays fixed'};
const DESIGN_AUDIT={
 visualArgument:'The student redistributes probability mass toward a fixed teacher while only student parameter cells change; deployment contains the student alone.',
 motion:'Student bars rise and fall on a common probability scale, student parameter cells update, and only the small model enters the device.',
 example:'A fixed teacher [0.65,0.25,0.10] guides an illustrative student trajectory from [0.33,0.34,0.33] to [0.60,0.27,0.13].',
 antiTemplate:'This depicts learning from full distributions rather than a confidence decision or a structural channel removal.',
 sceneRationale:'Four scenes establish the frozen reference, show classwise mismatch, demonstrate student-only learning, and separate training from deployment.'
};
const LearnPage:React.FC<{title:string;copy:string[];note:string;children:React.ReactNode}>=({title,copy,note,children})=>{const f=useCurrentFrame();return <div data-root style={{height:'100%',boxSizing:'border-box',padding:'110px 108px',display:'grid',gridTemplateColumns:'610px 960px',gap:132,alignItems:'center',background:COLORS.bg0,fontFamily:FONT}}><aside><div data-k="text" style={{opacity:fadeIn(f,2,12),fontSize:22,color:COLORS.primary,letterSpacing:3}}>EDGE AI · DISTILLATION</div><h1 data-k="text" style={{opacity:fadeIn(f,12,15),fontSize:55,lineHeight:1.18,margin:'30px 0 42px',color:COLORS.textStrong}}>{title}</h1>{copy.map((t,i)=><p data-k="text" key={t} style={{opacity:fadeIn(f,24+i*10,14),fontSize:30,lineHeight:1.45,color:COLORS.textMuted,margin:'0 0 28px'}}>{t}</p>)}<p data-k="text" style={{opacity:fadeIn(f,45,14),fontSize:23,lineHeight:1.45,color:COLORS.accent,marginTop:45}}>{note}</p></aside><aside style={{opacity:fadeIn(f,12,15)}}>{children}</aside></div>};
const ProbabilityCompare:React.FC<{frame:number}>=({frame})=>{
 const s=distillationState(frame);
 return <svg data-k="figure" width={960} height={665} viewBox="0 0 960 665"><text x={20} y={45} fill={COLORS.alt} fontSize={29}>FIXED TEACHER</text><text x={20} y={360} fill={COLORS.primary} fontSize={29}>LEARNING STUDENT</text>{[{scores:s.teacher,base:235,color:COLORS.alt},{scores:s.student,base:550,color:COLORS.primary}].map((row,r)=><g key={r}><line x1={150} x2={895} y1={row.base} y2={row.base} stroke={COLORS.axis} strokeWidth={2}/>{row.scores.map((p,i)=><g key={i}><rect x={195+i*245} y={row.base-p*220} width={115} height={p*220} fill={alpha(row.color,.75)}/><text x={218+i*245} y={row.base-p*220-22} fontSize={30} fill={COLORS.textStrong}>{p.toFixed(2)}</text><text x={218+i*245} y={row.base+40} fontSize={28} fill={COLORS.textMuted}>{T.classes[i]}</text></g>)}</g>)}<text x={20} y={640} fill={COLORS.accent} fontSize={26}>Same probability scale · each distribution sums to 1</text></svg>;
};
const Teacher:React.FC<{frame:number}>=({frame})=>{
 const s=distillationState(frame);
 return <LearnPage title={T.title} copy={['A pretrained teacher provides soft targets.','They contain more class information than a single winning label.']} note="Model sizes and probabilities are illustrative."><svg data-k="figure" width={960} height={675} viewBox="0 0 960 675"><text x={20} y={45} fontSize={29} fill={COLORS.textStrong}>SAME TRAINING INPUT</text><rect x={30} y={85} width={230} height={90} rx={16} fill={alpha(COLORS.primary,.2)} stroke={COLORS.primary} strokeWidth={3}/><text x={85} y={142} fill={COLORS.textStrong} fontSize={32}>Cat image</text><text x={30} y={265} fontSize={30} fill={COLORS.alt}>Teacher · 1000 params</text>{Array.from({length:30},(_,i)=><rect key={i} x={35+(i%10)*45} y={295+Math.floor(i/10)*45} width={31} height={31} fill={COLORS.alt}/>)}<text x={570} y={265} fontSize={30} fill={COLORS.primary}>Student · 100 params</text>{[0,1,2].map(i=><rect key={i} x={595+i*65} y={310} width={43} height={43} fill={COLORS.primary}/>)}<text x={30} y={495} fontSize={29} fill={COLORS.textStrong}>{T.fixed}</text>{s.teacher.map((p,i)=><g key={i}><rect x={30+i*280} y={540} width={245} height={83} rx={10} fill={alpha(COLORS.alt,.2)} stroke={COLORS.alt}/><text x={50+i*280} y={594} fill={COLORS.textStrong} fontSize={31}>{T.classes[i]} {p.toFixed(2)}</text></g>)}</svg></LearnPage>;
};
const Mismatch:React.FC<{frame:number}>=({frame})=><LearnPage title="Compare every class" copy={['The student begins with a different probability distribution.','Soft targets reveal which alternatives the teacher considers similar.']} note="Teacher and student see the same example."><ProbabilityCompare frame={180+frame}/></LearnPage>;
const Learn:React.FC<{frame:number}>=({frame})=>{
 const s=distillationState(360+frame);
 return <LearnPage title="Only the student updates" copy={['Soft-target loss guides the student toward the teacher.','Training often combines this with a label loss.']} note={`Illustrative training trajectory · disagreement ${s.gap.toFixed(2)}`}><div><ProbabilityCompare frame={360+frame}/><svg data-k="figure" viewBox="0 0 960 100" width={960} height={100}><text x={20} y={48} fill={COLORS.textMuted} fontSize={26}>Student parameters</text>{s.studentParameters.map((p,i)=><g key={i}><rect x={335+i*190} y={12} width={155} height={65} fill={alpha(COLORS.accent,.15)} stroke={COLORS.accent}/><rect x={335+i*190} y={77-p*65} width={155} height={p*65} fill={COLORS.accent}/><text x={377+i*190} y={52} fill={COLORS.textStrong} fontSize={27}>{p.toFixed(2)}</text></g>)}</svg></div></LearnPage>;
};
const Deploy:React.FC<{frame:number}>=({frame})=>{
 const s=distillationState(720+frame),move=Math.min(1,frame/55),x=90+move*300;
 return <LearnPage title="Deploy the student alone" copy={['The edge device runs the smaller learned model.','The teacher is only needed for training.']} note="Validate student accuracy on the deployment task."><svg data-k="figure" width={960} height={670} viewBox="0 0 960 670"><text x={25} y={45} fill={COLORS.textMuted} fontSize={28}>TRAINING</text><text x={420} y={45} fill={COLORS.result} fontSize={28}>EDGE DEVICE</text><rect x={340} y={85} width={570} height={505} rx={35} fill={alpha(COLORS.result,.06)} stroke={COLORS.result} strokeWidth={4}/><rect x={20} y={110} width={240} height={90} rx={12} fill={alpha(COLORS.alt,.18)} stroke={COLORS.alt}/><text x={62} y={166} fill={COLORS.alt} fontSize={32}>Teacher</text><g transform={`translate(${x} 0)`}><rect x={0} y={240} width={260} height={100} rx={16} fill={alpha(COLORS.primary,.2)} stroke={COLORS.primary} strokeWidth={3}/><text x={42} y={302} fill={COLORS.textStrong} fontSize={35}>Student</text></g>{move===1&&s.student.map((p,i)=><g key={i}><rect x={390+i*155} y={470-p*140} width={95} height={p*140} fill={COLORS.primary}/><text x={400+i*155} y={445-p*140} fill={COLORS.textStrong} fontSize={26}>{p.toFixed(2)}</text><text x={400+i*155} y={518} fill={COLORS.textMuted} fontSize={26}>{T.classes[i]}</text></g>)}<text x={25} y={645} fill={COLORS.result} fontSize={29}>Inference has no teacher dependency.</text></svg></LearnPage>;
};
export const SCENES:SceneDef[]=[{id:'teacher',Comp:Teacher,dur:180},{id:'mismatch',Comp:Mismatch,dur:180},{id:'learn',Comp:Learn,dur:360},{id:'deploy',Comp:Deploy,dur:180}];
