import React from 'react';
import {useCurrentFrame} from 'remotion';
import {COLORS,FONT,alpha,fadeIn} from '../theme';
import type {SceneDef} from '../Video';
import {pruningState} from '../mechanisms/edge09-pruning-state';
const T={title:'Prune a channel, not just a value',selected:'c1',output:'Downstream output'};
const DESIGN_AUDIT={
 visualArgument:'Removing channel c1 also removes its entire downstream input column, after which both tensors compact and the smaller product is recomputed.',
 motion:'A paired channel and matrix slice disappear; surviving columns close the gap and fewer multiplication terms contribute to changed output values.',
 example:'[2,.1,1,3] and a 2x4 matrix become [2,1,3] and 2x3; outputs change from [7.02,7.03] to [7,7].',
 antiTemplate:'Dimension deletion and index correspondence differ from numerical quantization and from changing probability heights.',
 sceneRationale:'Four scenes are necessary to establish the dependency, select the paired slice, physically compact it, and validate recomputed outputs and cost.'
};
const PrunePage:React.FC<{heading:string;paragraphs:string[];footer:string;children:React.ReactNode}>=({heading,paragraphs,footer,children})=>{const f=useCurrentFrame();return <div data-root style={{height:'100%',boxSizing:'border-box',padding:'110px 108px',display:'grid',gridTemplateColumns:'610px 960px',gap:132,alignItems:'center',background:COLORS.bg0,fontFamily:FONT}}><section><div data-k="text" style={{opacity:fadeIn(f,2,12),fontSize:22,letterSpacing:3,color:COLORS.primary}}>EDGE AI · STRUCTURE</div><h1 data-k="text" style={{opacity:fadeIn(f,12,15),fontSize:55,lineHeight:1.18,margin:'30px 0 42px',color:COLORS.textStrong}}>{heading}</h1>{paragraphs.map((t,i)=><p data-k="text" key={t} style={{opacity:fadeIn(f,24+i*10,14),fontSize:30,lineHeight:1.45,margin:'0 0 28px',color:COLORS.textMuted}}>{t}</p>)}<p data-k="text" style={{opacity:fadeIn(f,45,14),fontSize:23,lineHeight:1.45,marginTop:45,color:COLORS.accent}}>{footer}</p></section><section style={{opacity:fadeIn(f,12,15)}}>{children}</section></div>};
const TensorDiagram:React.FC<{frame:number}>=({frame})=>{
 const s=pruningState(frame);
 return <svg data-k="figure" width={960} height={660} viewBox="0 0 960 660"><text x={20} y={42} fontSize={30} fill={COLORS.textStrong}>LAYER A · {s.features.length} output channels</text>{s.indices.map((channel,i)=><g key={channel}><text x={245+s.positions[i]*160} y={98} fill={s.selected===channel?COLORS.warn:COLORS.textMuted} fontSize={27}>c{channel}</text><rect x={215+s.positions[i]*160} y={123} width={125} height={87} rx={10} fill={alpha(s.selected===channel?COLORS.warn:COLORS.primary,.65)} stroke={s.selected===channel?COLORS.warn:COLORS.primary} strokeWidth={3}/><text x={257+s.positions[i]*160} y={180} fill={COLORS.textStrong} fontSize={35}>{s.features[i]}</text><line x1={278+s.positions[i]*160} x2={278+s.positions[i]*160} y1={225} y2={310} stroke={s.selected===channel?COLORS.warn:COLORS.axis} strokeWidth={s.selected===channel?5:3}/>{s.weights.map((row,r)=><g key={r}><rect x={215+s.positions[i]*160} y={330+r*110} width={125} height={85} fill={alpha(s.selected===channel?COLORS.warn:COLORS.alt,.48)} stroke={s.selected===channel?COLORS.warn:COLORS.alt} strokeWidth={3}/><text x={254+s.positions[i]*160} y={385+r*110} fill={COLORS.textStrong} fontSize={33}>{row[i]}</text></g>)}</g>)}<text x={20} y={380} fontSize={26} fill={COLORS.textMuted}>Output 0</text><text x={20} y={490} fontSize={26} fill={COLORS.textMuted}>Output 1</text><text x={20} y={598} fontSize={29} fill={COLORS.textStrong}>LAYER B · weight matrix {s.shape.join(' × ')}</text></svg>;
};
const Connected:React.FC<{frame:number}>=({frame})=><PrunePage heading={T.title} paragraphs={['Each output channel feeds one input slice in the next layer.','Four channels feed two downstream outputs.']} footer="A channel is a structural dimension."><TensorDiagram frame={frame}/></PrunePage>;
const Select:React.FC<{frame:number}>=({frame})=><PrunePage heading="Select the matching slice" paragraphs={['Suppose channel c1 has low importance.','Mark both c1 and its downstream input column for removal.']} footer="Importance selection is illustrative."><TensorDiagram frame={180+frame}/></PrunePage>;
const Compact:React.FC<{frame:number}>=({frame})=>{
 const s=pruningState(360+frame);
 return <PrunePage heading="Remove. Then compact." paragraphs={['Delete c1 and the matching weight column together.','Surviving channels move into contiguous positions.']} footer={`Input width ${s.features.length} · downstream shape ${s.shape.join(' × ')}`}><TensorDiagram frame={360+frame}/></PrunePage>;
};
const Recompute:React.FC<{frame:number}>=({frame})=>{
 const s=pruningState(660+frame),count=Math.min(3,Math.floor(frame/24)+1);
 return <PrunePage heading="Smaller tensors, changed outputs" paragraphs={['The dense example now uses six multiply terms instead of eight.','Outputs shift. Validate accuracy and fine-tune.']} footer="Fewer terms do not guarantee a device speedup."><svg data-k="figure" width={960} height={670} viewBox="0 0 960 670"><text x={20} y={45} fill={COLORS.textStrong} fontSize={29}>COMPACT MATRIX × FEATURE VECTOR</text>{s.weights.map((row,r)=><g key={r}>{row.map((w,i)=><g key={i}><rect x={20+i*225} y={100+r*190} width={205} height={100} rx={12} fill={alpha(COLORS.alt,.18)} stroke={i<count?COLORS.result:COLORS.axis} strokeWidth={3}/><text x={45+i*225} y={160+r*190} fill={i<count?COLORS.textStrong:COLORS.textDim} fontSize={32}>{w} × {s.features[i]}</text></g>)}<text x={740} y={162+r*190} fill={COLORS.result} fontSize={43}>= {row.slice(0,count).reduce((n,w,i)=>n+w*s.features[i],0)}</text></g>)}<text x={20} y={540} fill={COLORS.textMuted} fontSize={29}>Before: [7.02, 7.03]</text><text x={20} y={603} fill={COLORS.result} fontSize={32}>After: [{s.output.join(', ')}] · {s.terms} multiply terms</text></svg></PrunePage>;
};
export const SCENES:SceneDef[]=[{id:'connected',Comp:Connected,dur:180},{id:'select',Comp:Select,dur:180},{id:'compact',Comp:Compact,dur:300},{id:'recompute',Comp:Recompute,dur:270}];
