import React from 'react';
import {COLORS,fadeIn,ramp} from '../theme';
import {Backdrop} from '../components/Backdrop';
import {Heading,Kicker,Lines,Chip} from '../components/ui';
import {RiscBoard,BitFields,DataTokens} from '../components/RiscV';
import {rv01State,RV01} from '../mechanisms/rv01-state';
import type {SceneDef} from '../Video';
const T={...RV01,hex:(w:number)=>'0x'+w.toString(16).toUpperCase().padStart(8,'0'),ranges:['31:25','24:20','19:15','14:12','11:7','6:0']};
const DESIGN_AUDIT={visualArgument:'Bit slices become decoded register indices and an operation; editing only rd redirects the destination.',motion:'Extract opcode, fan register fields into three decoded slots, combine function bits, then change actual rd bits.',example:'0x007302B3 is ADD x5,x6,x7; changing bits11:7 produces0x007304B3 and destinationx9.',antiTemplate:'This is a bit-slice decoding and controlled-edit lesson, not a register-storage or ALU arithmetic diagram.',sceneRationale:'Five scenes separate word partition, instruction class, register roles, operation decode and a destination-only edit; each adds a new decoding consequence.'};
function EncodingPage({f,title,copy,children}:{f:number;title:string;copy:string[];children:React.ReactNode}){return <div data-root><Backdrop width={1920} height={1080}/><Kicker text="RISC-V · INSTRUCTION ENCODING" frame={f}/><Heading text={title} frame={f} size={50} width={650}/><Lines items={copy} frame={f} top={345} width={615} size={30}/><div style={{position:'absolute',left:850,top:250,opacity:fadeIn(f,18,14)}}>{children}</div><div style={{position:'absolute',left:108,top:895}}><Chip text="RV32I · a 32-bit R-type word" opacity={fadeIn(f,38)}/></div></div>;}
function Word({frame:f}:{frame:number}){const s=rv01State(f);let x=35;return <EncodingPage f={f} title="One word. Several jobs." copy={['Each field has a fixed width.','Read bit positions from 31 down to 0.']}><RiscBoard><text x={35} y={35} fill={COLORS.textStrong} fontSize={34}>{T.hex(s.word)}</text><BitFields fields={s.fields} y={130}/>{s.fields.map((a,i)=>{const w=890*a.bits/32;const at=x+w/2;x+=w;return <text key={a.label} x={at} y={260} textAnchor="middle" fill={COLORS.textMuted} fontSize={22}>{T.ranges[i]}</text>;})}<DataTokens progress={fadeIn(f,55)} tokens={[{label:'Assembly',value:`ADD x${s.rd}, x${s.rs1}, x${s.rs2}`,x:150,y:385,width:640}]}/></RiscBoard></EncodingPage>;}
function Opcode({frame:f}:{frame:number}){const s=rv01State(150+f),p=ramp(f,30,65);return <EncodingPage f={f} title="First, select the class" copy={['The low seven bits identify the instruction class.','This word uses register-register arithmetic.']}><RiscBoard><BitFields fields={s.fields}/><DataTokens tokens={[{label:'opcode',value:s.fields[5].value,x:690-420*p,y:200+120*p,width:230}]}/><text x={65} y={500} fill={COLORS.accent} fontSize={32} opacity={fadeIn(f,92)}>0110011 → register-register</text></RiscBoard></EncodingPage>;}
function Registers({frame:f}:{frame:number}){const s=rv01State(300+f);return <EncodingPage f={f} title="Decode the register roles" copy={['rs1 and rs2 name the sources.','rd names the destination.']}><RiscBoard><BitFields fields={s.fields}/><DataTokens tokens={s.tokens}/><text x={50} y={505} fill={COLORS.textStrong} fontSize={30}>{s.decoded?`Sources: x${s.rs1}, x${s.rs2}   →   destination: x${s.rd}`:'Five bits select one of 32 registers.'}</text></RiscBoard></EncodingPage>;}
function FunctionBits({frame:f}:{frame:number}){const s=rv01State(510+f),p=ramp(f,35,70);return <EncodingPage f={f} title="Choose the operation" copy={['funct3 and funct7 refine the opcode.','Together these fields select ADD.']}><RiscBoard><BitFields fields={[s.fields[0],s.fields[3],s.fields[5]]} y={70}/><DataTokens tokens={[{label:'funct7',value:s.fields[0].value,x:75+65*p,y:220+80*p,width:250},{label:'funct3',value:s.fields[3].value,x:440-30*p,y:220+80*p,width:150}]}/><text x={605} y={355} fill={COLORS.result} fontSize={45} opacity={fadeIn(f,85)}>{s.operation}</text><text x={120} y={510} fill={COLORS.textStrong} fontSize={34} opacity={fadeIn(f,100)}>x{s.rd} ← x{s.rs1} + x{s.rs2}</text></RiscBoard></EncodingPage>;}
function Redirect({frame:f}:{frame:number}){const s=rv01State(690+f),old=rv01State(749);return <EncodingPage f={f} title="Edit only the destination" copy={['Change rd from x5 to x9.','The two sources and ADD operation stay fixed.']}><RiscBoard><BitFields fields={s.fields}/><DataTokens tokens={[{label:'rs1 unchanged',value:`x${s.rs1}`,x:60,y:260},{label:'rs2 unchanged',value:`x${s.rs2}`,x:340,y:260},{label:'decoded rd',value:`x${s.rd}`,x:670,y:260}]}/><text x={55} y={445} fill={COLORS.textMuted} fontSize={28}>Before: {T.hex(old.word)} · rd = x{old.rd}</text><text x={55} y={515} fill={COLORS.result} fontSize={32}>Now: {T.hex(s.word)} · rd = x{s.rd}</text></RiscBoard></EncodingPage>;}
export const SCENES:SceneDef[]=[{id:'word',Comp:Word,dur:150},{id:'opcode',Comp:Opcode,dur:150},{id:'registers',Comp:Registers,dur:210},{id:'function',Comp:FunctionBits,dur:180},{id:'redirect',Comp:Redirect,dur:210}];
