import React from 'react';
import {COLORS,fadeIn,ramp,alpha} from '../theme';
import {Backdrop} from '../components/Backdrop';
import {Heading,Kicker,Lines,Chip} from '../components/ui';
import {RiscBoard,RegisterBank,DataTokens} from '../components/RiscV';
import {rv02State,RV02} from '../mechanisms/rv02-state';
import type {SceneDef} from '../Video';
const T={...RV02,readA:6,readB:7,destination:5};
const DESIGN_AUDIT={visualArgument:'Two reads copy stored values; pending write data becomes one register value only at an edge, and x0 cannot retain a write.',motion:'Copy9 and4 into independent ports, form13, transfer into x5 at the edge and discard a later x0 payload.',example:'x6=9 andx7=4 produce13; x5 stays0 until the edge whilex0 remains0 forever.',antiTemplate:'This uses actual storage rows and nondestructive copies, unlike encoding bit extraction or load-memory address selection.',sceneRationale:'Five scenes distinguish read selection, simultaneous value transfer, pending data, edge commit and the special zero-register behavior.'};
function PortPage({f,title,lines,children}:{f:number;title:string;lines:string[];children:React.ReactNode}){return <div data-root><Backdrop width={1920} height={1080} tint={COLORS.accent}/><Kicker frame={f} text="RISC-V · REGISTER FILE"/><Heading frame={f} text={title} size={50} width={650}/><Lines frame={f} items={lines} top={345} width={615} size={30}/><div style={{position:'absolute',left:850,top:250,opacity:fadeIn(f,16)}}>{children}</div><div style={{position:'absolute',left:108,top:875}}><Chip text="Illustrative 2-read / 1-write implementation" opacity={fadeIn(f,42)} size={22}/></div></div>;}
function Select({frame:f}:{frame:number}){const s=rv02State(f),p=ramp(f,40,60);return <PortPage f={f} title="Two addresses, two values" lines={['Read A selects x6.','Read B independently selects x7.']}><RiscBoard><RegisterBank values={s.values} readIndices={p>.5?s.readIndices:[]} width={330}/><DataTokens tokens={[{label:'Read A address',value:T.readA,x:610-130*p,y:150},{label:'Read B address',value:T.readB,x:610-130*p,y:280}]}/><text x={50} y={450} fill={COLORS.textStrong} fontSize={30}>Both addresses apply together.</text><text x={50} y={515} fill={COLORS.textMuted} fontSize={26}>The stored values are still {s.readA} and {s.readB}.</text></RiscBoard></PortPage>;}
function ReadPorts({frame:f}:{frame:number}){const s=rv02State(150+f);return <PortPage f={f} title="Read without removing" lines={['Copies travel to the two output ports.','The source registers keep their values.']}><RiscBoard><RegisterBank values={s.values} readIndices={s.readIndices} width={320}/><DataTokens tokens={s.tokens.map(t=>({...t,width:160}))}/><text x={480} y={335} fill={COLORS.accent} fontSize={29}>A = {s.readA}   B = {s.readB}</text><text x={40} y={485} fill={COLORS.textMuted} fontSize={28}>Stored x6 = {s.values[2].value}</text><text x={40} y={545} fill={COLORS.textMuted} fontSize={28}>Stored x7 = {s.values[3].value}</text></RiscBoard></PortPage>;}
function Pending({frame:f}:{frame:number}){const s=rv02State(330+f),p=ramp(f,20,95);return <PortPage f={f} title="Ready is not yet stored" lines={['The two values produce write data.','x5 remains unchanged before the edge.']}><RiscBoard><RegisterBank values={s.values} writeIndex={5} width={300}/><DataTokens tokens={[{label:'Read A',value:s.readA,x:440,y:75},{label:'Read B',value:s.readB,x:690,y:75}]}/><text x={615} y={235} textAnchor="middle" fontSize={40} fill={COLORS.accent}>+</text><DataTokens tokens={[{label:'Pending x5 write',value:s.ready?s.sum:'—',x:560,y:290+50*p,width:250}]}/><text x={40} y={530} fill={COLORS.textStrong} fontSize={31}>Stored x5 = {s.values[1].value}</text></RiscBoard></PortPage>;}
function WriteEdge({frame:f}:{frame:number}){const s=rv02State(540+f),approach=ramp(f,15,45);return <PortPage f={f} title="One edge writes one row" lines={['The enabled write targets x5.','At the rising edge, 0 becomes 13.']}><RiscBoard><RegisterBank values={s.values} writeIndex={5} width={340}/>{!s.written&&<DataTokens tokens={[{label:'Write data',value:s.sum,x:640-210*approach,y:220,width:200}]}/>}<path d="M55 435 H280 V380 H510" fill="none" stroke={COLORS.axis} strokeWidth={4}/><circle cx={s.written?380:260} cy={s.written?380:435} r={12} fill={COLORS.result}/><text x={55} y={515} fill={COLORS.textStrong} fontSize={31}>x5: {s.written?`${0} → ${s.sum}`:'0 · waiting for edge'}</text></RiscBoard></PortPage>;}
function Zero({frame:f}:{frame:number}){const s=rv02State(720+f),p=ramp(f,25,65);return <PortPage f={f} title="x0 never keeps a write" lines={['An attempted write carries 13 to x0.','The payload is discarded; x0 stays zero.']}><RiscBoard><RegisterBank values={s.values} writeIndex={0} width={340}/>{!s.discarded&&<DataTokens tokens={[{label:'Attempt: write x0',value:s.sum,x:660-280*p,y:80,width:240}]}/>}<g opacity={s.discarded?1:0}><path d="M480 95 L560 175 M560 95 L480 175" stroke={COLORS.warn} strokeWidth={8}/><text x={475} y={250} fill={COLORS.warn} fontSize={29}>Payload discarded</text></g><rect x={440} y={340} width={400} height={100} rx={12} fill={alpha(COLORS.result,.12)} stroke={COLORS.result}/><text x={480} y={402} fill={COLORS.result} fontSize={36}>Read x0 = {s.values[0].value}</text><text x={40} y={535} fill={COLORS.textMuted} fontSize={27}>x5 still holds {s.values[1].value}.</text></RiscBoard></PortPage>;}
export const SCENES:SceneDef[]=[{id:'select',Comp:Select,dur:150},{id:'read',Comp:ReadPorts,dur:180},{id:'pending',Comp:Pending,dur:210},{id:'edge',Comp:WriteEdge,dur:180},{id:'zero',Comp:Zero,dur:180}];
