import React from 'react';
import {COLORS,fadeIn,ramp} from '../theme';
import {Backdrop} from '../components/Backdrop';
import {Heading,Kicker,Lines,Chip} from '../components/ui';
import {RiscBoard,BitFields,DataTokens} from '../components/RiscV';
import {rv03State,RV03,decodeI,decodeS,decodeB} from '../mechanisms/rv03-state';
import type {SceneDef} from '../Video';
const T={...RV03,bin:(n:number,w:number)=>n.toString(2).padStart(w,'0'),hex:(n:number)=>'0x'+(n>>>0).toString(16).toUpperCase().padStart(8,'0')};
const DESIGN_AUDIT={visualArgument:'Visible bit fragments are copied, sign-filled, joined or permuted until they form actual signed32-bit offsets.',motion:'Lift I bits, replicate their sign, bring separated S fields together, and reorder B fields with an appended zero.',example:'ADDI -4 producesFFFFFFFC; SW +12 joins7+5bits; BEQ +16 orders0|0|000000|1000|0.',antiTemplate:'This lesson operates on bit-string reconstruction, not register-index selection, ALU calculation or PC update.',sceneRationale:'Six scenes distinguish I extraction from sign extension, S isolation from concatenation, B permutation and a completed-output comparison.'};
function ImmediatePage({f,title,words,children}:{f:number;title:string;words:string[];children:React.ReactNode}){return <div data-root><Backdrop width={1920} height={1080}/><Kicker frame={f} text="RISC-V · IMMEDIATE GENERATION"/><Heading frame={f} text={title} width={650} size={50}/><Lines frame={f} items={words} top={345} width={615} size={30}/><div style={{position:'absolute',left:850,top:250,opacity:fadeIn(f,20)}}>{children}</div><div style={{position:'absolute',left:108,top:875}}><Chip text="Instruction bits → signed byte offset" color={COLORS.accent} opacity={fadeIn(f,42)}/></div></div>;}
function ISlice({frame:f}:{frame:number}){const s=rv03State(f),p=ramp(f,35,70);return <ImmediatePage f={f} title="I-type: lift one slice" words={['ADDI encodes its offset in bits 31:20.','Keep the twelve bits in order.']}><RiscBoard><text x={35} y={40} fontSize={31} fill={COLORS.textStrong}>ADDI x5, x6, {decodeI(T.iWord)}</text><BitFields y={125} fields={[{label:'imm',bits:12,value:T.bin(s.iRaw,12)},{label:'rs1',bits:5,value:'00110'},{label:'funct3',bits:3,value:'000'},{label:'rd',bits:5,value:'00101'},{label:'opcode',bits:7,value:'0010011'}]}/><DataTokens tokens={[{label:'inst[31:20] → imm[11:0]',value:T.bin(s.iRaw,12),x:35+90*p,y:275+70*p,width:600}]}/><text x={40} y={535} fill={COLORS.textMuted} fontSize={28}>The instruction word is {T.hex(T.iWord)}.</text></RiscBoard></ImmediatePage>;}
function Sign({frame:f}:{frame:number}){const s=rv03State(150+f);return <ImmediatePage f={f} title="Extend the sign" words={['The top immediate bit is 1.','Copy it into the upper twenty positions.']}><RiscBoard><DataTokens tokens={[{label:'inst[31]: sign',value:s.sign,x:45,y:60,width:230},{label:'12-bit source',value:T.bin(s.iRaw,12),x:345,y:60,width:545}]}/><BitFields fields={s.iFields} y={290}/><text x={45} y={475} fill={COLORS.result} fontSize={39}>{s.iOutput===null?'Upper bits are not filled yet.':`${T.hex(s.iOutput)} = ${s.iOutput}`}</text><text x={45} y={545} fill={COLORS.textMuted} fontSize={27}>A negative value stays negative.</text></RiscBoard></ImmediatePage>;}
function SplitS({frame:f}:{frame:number}){const s=rv03State(330+f),p=ramp(f,30,75);return <ImmediatePage f={f} title="S-type: find both pieces" words={['A store splits the immediate around other fields.','The high seven and low five bits belong together.']}><RiscBoard><text x={35} y={35} fill={COLORS.textStrong} fontSize={31}>SW x5, {decodeS(T.sWord)}(x6)</text><BitFields y={130} fields={[{label:'imm hi',bits:7,value:T.bin(s.sHigh,7)},{label:'rs2',bits:5,value:'00101'},{label:'rs1',bits:5,value:'00110'},{label:'funct3',bits:3,value:'010'},{label:'imm lo',bits:5,value:T.bin(s.sLow,5)},{label:'opcode',bits:7,value:'0100011'}]}/><DataTokens tokens={[{label:'inst[31:25]',value:T.bin(s.sHigh,7),x:50,y:270+70*p,width:290},{label:'inst[11:7]',value:T.bin(s.sLow,5),x:600,y:270+70*p,width:250}]}/><text x={45} y={530} fill={COLORS.textMuted} fontSize={27}>Register bits are not part of the immediate.</text></RiscBoard></ImmediatePage>;}
function JoinS({frame:f}:{frame:number}){const s=rv03State(480+f);return <ImmediatePage f={f} title="Join high bits with low bits" words={['Preserve the order inside each fragment.','A zero sign bit fills the upper bits with zeros.']}><RiscBoard><text x={40} y={55} fill={COLORS.textStrong} fontSize={31}>S immediate: 7 high bits + 5 low bits</text><DataTokens tokens={s.sTokens}/><text x={50} y={445} fontSize={34} fill={COLORS.result}>{s.sOutput===null?'The fragments are moving together.':`${T.bin((s.sHigh<<5)|s.sLow,12)} = +${s.sOutput}`}</text><text x={50} y={525} fontSize={29} fill={COLORS.textMuted}>{s.sOutput===null?'':`${T.hex(s.sOutput)} is the 32-bit offset.`}</text></RiscBoard></ImmediatePage>;}
function BranchBits({frame:f}:{frame:number}){const s=rv03State(630+f);return <ImmediatePage f={f} title="B-type: rearrange the bits" words={['inst[7] becomes the high bit imm[11].','Append a fixed zero at imm[0].']}><RiscBoard><text x={35} y={35} fill={COLORS.textStrong} fontSize={30}>BEQ x1, x2, +{decodeB(T.bWord)}</text><text x={40} y={115} fill={COLORS.textMuted} fontSize={25}>Sources: inst[31], inst[7], inst[30:25], inst[11:8]</text><text x={40} y={185} fill={COLORS.accent} fontSize={28}>Destination order: 12 | 11 | 10:5 | 4:1 | 0</text><DataTokens tokens={s.bTokens}/>{s.bLowZero&&<DataTokens tokens={[{label:'imm0',value:'0',x:805,y:450,width:100}]}/>}<text x={40} y={580} fill={COLORS.result} fontSize={30}>{s.bOutput===null?'Bit fragments move into place.':`${s.bParts.map(q=>q.value).join('')} = +${s.bOutput} bytes`}</text></RiscBoard></ImmediatePage>;}
function Values({frame:f}:{frame:number}){const s=rv03State(810+f),p=ramp(f,20,35);return <ImmediatePage f={f} title="Different routes, usable offsets" words={['The instruction format controls the wiring.','Each result is a signed byte offset.']}><RiscBoard><DataTokens tokens={[{label:'I-type · sign extend',value:`${s.iValue} · ${T.hex(s.iValue)}`,x:100+25*p,y:80,width:690},{label:'S-type · concatenate',value:`+${s.sValue} · ${T.hex(s.sValue)}`,x:100+25*p,y:260,width:690},{label:'B-type · reorder + zero',value:`+${s.bValue} · ${T.hex(s.bValue)}`,x:100+25*p,y:440,width:690}]}/></RiscBoard></ImmediatePage>;}
export const SCENES:SceneDef[]=[{id:'islice',Comp:ISlice,dur:150},{id:'sign',Comp:Sign,dur:180},{id:'split',Comp:SplitS,dur:150},{id:'join',Comp:JoinS,dur:150},{id:'branch',Comp:BranchBits,dur:180},{id:'values',Comp:Values,dur:90}];
