import React from 'react';
import {COLORS,fadeIn,ramp,alpha} from '../theme';
import {Backdrop} from '../components/Backdrop';
import {Heading,Kicker,Lines} from '../components/ui';
import {RiscBoard,BitFields,DataTokens} from '../components/RiscV';
import {rv04State,RV04,aluDecode} from '../mechanisms/rv04-state';
import type {SceneDef} from '../Video';
const T={...RV04,bin:(n:number,w:number)=>n.toString(2).padStart(w,'0'),operations:[RV04.addWord,RV04.subWord,RV04.xorWord]};
const DESIGN_AUDIT={visualArgument:'Fixed12 and5 yield different concrete results when function fields select addition, subtraction or bitwise XOR.',motion:'Join counted sets for ADD, remove five units for SUB, then evaluate aligned bit columns for XOR.',example:'Control pairs000/0000000,000/0100000,100/0000000 produce17,7,9.',antiTemplate:'Quantity joining, removal and bit-column evaluation explain ALU control, unlike register-storage or immediate reconstruction.',sceneRationale:'Four scenes provide the ADD baseline, a funct7-only SUB change, a bitwise operation and a control/result comparison.'};
function AluPage({f,title,copy,children}:{f:number;title:string;copy:string[];children:React.ReactNode}){return <div data-root><Backdrop width={1920} height={1080} tint={COLORS.result}/><Kicker frame={f} text="RISC-V · ALU CONTROL"/><Heading text={title} frame={f} width={650} size={50}/><Lines frame={f} items={copy} top={345} width={615} size={30}/><div style={{position:'absolute',left:850,top:250,opacity:fadeIn(f,18)}}>{children}</div><div data-k="text" style={{position:'absolute',left:108,top:885,color:COLORS.accent,fontSize:27,opacity:fadeIn(f,45)}}>Fixed operands: A = {T.a}, B = {T.b}</div></div>;}
function Add({frame:f}:{frame:number}){const s=rv04State(f),p=ramp(f,40,80);return <AluPage f={f} title="Decode ADD, then compute" copy={['Opcode selects register-register arithmetic.','The function fields choose addition.']}><RiscBoard><BitFields fields={s.fields} y={65}/><DataTokens tokens={[{label:'A',value:s.a,x:80,y:205},{label:'B',value:s.b,x:640,y:205}]}/>{Array.from({length:T.a},(_,i)=><rect key={'a'+i} x={65+i*39} y={340} width={29} height={36} fill={COLORS.primary}/>)}{Array.from({length:T.b},(_,i)=><rect key={'b'+i} x={655+i*39+(533-655)*p} y={340} width={29} height={36} fill={COLORS.accent}/>)}<text x={65} y={460} fill={COLORS.result} fontSize={39}>{s.a} {s.symbol} {s.b} = {s.result??'—'}</text><text x={65} y={540} fill={COLORS.textMuted} fontSize={26}>The output follows the decoded operation.</text></RiscBoard></AluPage>;}
function Subtract({frame:f}:{frame:number}){const s=rv04State(240+f),p=ramp(f,90,65);return <AluPage f={f} title="One function field flips" copy={['Keep opcode and funct3 unchanged.','funct7 = 0100000 selects subtraction.']}><RiscBoard><BitFields fields={s.fields} y={65}/><text x={45} y={235} fill={COLORS.textStrong} fontSize={34}>{s.a} {s.symbol} {s.b} = {s.result??'—'}</text>{Array.from({length:s.op==='ADD'?s.unitCount:T.a},(_,i)=>{const removed=s.op==='SUB'&&i>=T.a-T.b;return <rect key={i} x={50+i*43} y={315+(removed?115*p:0)} width={30} height={40} fill={removed?COLORS.warn:COLORS.primary}/>;})}<text x={50} y={540} fill={COLORS.result} fontSize={29}>{s.op==='SUB'?`${T.b} units removed; ${s.result} remain.`:'Before the field change: ADD result.'}</text></RiscBoard></AluPage>;}
function Xor({frame:f}:{frame:number}){const s=rv04State(480+f),ready=s.op==='XOR';return <AluPage f={f} title="Choose a bitwise operation" copy={['funct3 = 100 selects XOR in this class.','A result bit is 1 when its input bits differ.']}><RiscBoard><BitFields fields={s.fields} y={50} height={72}/>{[{name:'A',bits:s.aBits,y:210},{name:'B',bits:s.bBits,y:315},{name:'XOR',bits:ready?s.resultBits:[],y:435}].map(row=><g key={row.name}><text x={30} y={row.y+42} fill={COLORS.textMuted} fontSize={28}>{row.name}</text>{[0,1,2,3].map(i=><g key={i}><rect x={200+i*145} y={row.y} width={105} height={65} rx={8} stroke={COLORS.accent} fill={alpha(COLORS.accent,.1)}/><text x={252+i*145} y={row.y+45} textAnchor="middle" fill={row.name==='XOR'?COLORS.result:COLORS.textStrong} fontSize={36}>{row.bits[i]??'—'}</text></g>)}</g>)}<text x={45} y={570} fill={COLORS.textMuted} fontSize={25}>{ready?`Low 4 bits: ${s.resultBits.join('')} = ${s.result}; upper 28 bits are 0.`:'The same input bits await the XOR selection.'}</text></RiscBoard></AluPage>;}
function Compare({frame:f}:{frame:number}){const rows=T.operations.map(w=>({...aluDecode(w,T.a,T.b),funct3:(w>>>12)&7,funct7:w>>>25}));return <AluPage f={f} title="Fields select behavior" copy={['The opcode is the same in all three rows.','Function bits change the operation and its result.']}><RiscBoard><text x={40} y={35} fontSize={30} fill={COLORS.accent}>Common opcode: {T.bin(T.addWord&127,7)}</text><text x={40} y={125} fontSize={25} fill={COLORS.textMuted}>Operation</text><text x={280} y={125} fontSize={25} fill={COLORS.textMuted}>funct3 / funct7</text><text x={700} y={125} fontSize={25} fill={COLORS.textMuted}>Result</text>{rows.map((row,i)=><g key={row.name} opacity={fadeIn(f,25+i*10)}><rect x={35} y={155+i*125} width={850} height={95} rx={10} fill={alpha(COLORS.primary,.09)} stroke={COLORS.axis}/><text x={65} y={213+i*125} fill={COLORS.textStrong} fontSize={33}>{row.name}</text><text x={280} y={213+i*125} fill={COLORS.accent} fontSize={29}>{T.bin(row.funct3,3)} / {T.bin(row.funct7,7)}</text><text x={740} y={213+i*125} fill={COLORS.result} fontSize={39}>{row.result}</text></g>)}</RiscBoard></AluPage>;}
export const SCENES:SceneDef[]=[{id:'add',Comp:Add,dur:240},{id:'subtract',Comp:Subtract,dur:240},{id:'xor',Comp:Xor,dur:240},{id:'compare',Comp:Compare,dur:180}];
