import React from 'react';
import {COLORS,fadeIn,ramp} from '../theme';
import {Backdrop} from '../components/Backdrop';
import {Heading,Kicker,Lines,Chip} from '../components/ui';
import {RiscBoard,RegisterBank,MemoryWords,DataTokens} from '../components/RiscV';
import {rv05State,RV05,hex} from '../mechanisms/rv05-state';
import type {SceneDef} from '../Video';
const T={...RV05,nextPc:RV05.pc+4,assembly:`LW x${RV05.rd}, ${RV05.offset}(x6)`};
const DESIGN_AUDIT={visualArgument:'One load selects an instruction, computes an address, copies memory data and commits x5 and PC together at a single edge.',motion:'Address tokens select concrete rows, the42 payload moves toward writeback, and two stored values change simultaneously.',example:'PC0x200 andx6=0x1000 withoffset8 select memory0x1008=42; one edge setsx5=42 andPC=0x204.',antiTemplate:'A continuous cycle rail and pending/storage separation distinguish one-cycle propagation from pipeline stages or address arithmetic.',sceneRationale:'Six views separate fetch, base read, address calculation, memory read, pending writeback and one completion edge without implying six clocks.'};
function CyclePage({f,absolute,title,copy,children}:{f:number;absolute:number;title:string;copy:string[];children:React.ReactNode}){const s=rv05State(absolute);return <div data-root><Backdrop width={1920} height={1080}/><Kicker frame={f} text="RISC-V · SINGLE-CYCLE DATAPATH"/><Heading frame={f} text={title} size={50} width={650}/><Lines frame={f} items={copy} top={345} width={615} size={30}/><div style={{position:'absolute',left:850,top:250,opacity:fadeIn(f,18)}}>{children}</div><div data-k="figure" style={{position:'absolute',left:110,top:800,width:600,height:70}}><svg width={600} height={70}><path d="M4 50 H595" stroke={COLORS.axis} strokeWidth={4}/><path d={`M4 50 H${4+590*s.cycleProgress}`} stroke={COLORS.accent} strokeWidth={6}/><path d="M590 50 V12" stroke={s.committed?COLORS.result:COLORS.axis} strokeWidth={5}/><text x={2} y={24} fill={COLORS.textMuted} fontSize={24}>One clock cycle</text></svg></div><div style={{position:'absolute',left:108,top:905}}><Chip text="Illustrative combinational-memory implementation" size={21} opacity={fadeIn(f,40)}/></div></div>;}
function Fetch({frame:f}:{frame:number}){const s=rv05State(f),p=ramp(f,35,70);return <CyclePage f={f} absolute={f} title="Fetch the current word" copy={[T.assembly,'PC selects the instruction at 0x200.']}><RiscBoard><MemoryWords words={[{address:hex(T.pc),value:hex(T.word)}]} selectedAddress={hex(T.pc)} x={410} y={85} width={490}/><DataTokens tokens={[{label:'PC address',value:hex(s.pc),x:50+150*p,y:250-70*p}]}/><DataTokens progress={fadeIn(f,90)} tokens={[{label:'Decoded instruction',value:T.assembly,x:125,y:410,width:690}]}/><text x={430} y={40} fill={COLORS.textMuted} fontSize={27}>Instruction memory</text></RiscBoard></CyclePage>;}
function ReadBase({frame:f}:{frame:number}){const s=rv05State(150+f),p=ramp(f,35,75);return <CyclePage f={f} absolute={150+f} title="Read base and offset" copy={['x6 supplies the base address.','The instruction supplies a signed offset of 8.']}><RiscBoard><RegisterBank values={s.values} readIndices={[6]} width={325}/><DataTokens tokens={[{label:'Base copy',value:hex(s.base),x:370+150*p,y:225},{label:'Signed offset',value:s.offset,x:520,y:395}]}/><text x={40} y={525} fill={COLORS.textMuted} fontSize={27}>Stored x5 is still {s.rdValue}.</text></RiscBoard></CyclePage>;}
function Address({frame:f}:{frame:number}){const s=rv05State(300+f);return <CyclePage f={f} absolute={300+f} title="Compute the byte address" copy={['Add the base and sign-extended offset.','The address chooses data; it is not the data.']}><RiscBoard><DataTokens tokens={[{label:'Base',value:hex(s.base),x:55,y:105,width:290},{label:'Offset',value:s.offset,x:590,y:105,width:230}]}/><text x={455} y={157} fill={COLORS.accent} fontSize={42}>+</text><DataTokens tokens={[{label:'Effective address',value:s.address===null?'—':hex(s.address),x:265,y:340,width:410}]}/><text x={40} y={530} fill={COLORS.textMuted} fontSize={28}>No register has been written.</text></RiscBoard></CyclePage>;}
function Memory({frame:f}:{frame:number}){const s=rv05State(450+f);return <CyclePage f={f} absolute={450+f} title="Read the selected word" copy={['Address 0x1008 selects the row containing 42.','Reading copies the word; memory keeps it.']}><RiscBoard><MemoryWords words={s.words} selectedAddress={s.selectedAddress}/><DataTokens tokens={[{label:'Read address',value:hex(T.base+T.offset),x:45,y:90,width:280}]}/><DataTokens tokens={[s.dataToken]}/><text x={45} y={520} fill={COLORS.result} fontSize={33}>Read data = {s.data??'—'}</text></RiscBoard></CyclePage>;}
function Writeback({frame:f}:{frame:number}){const s=rv05State(600+f);return <CyclePage f={f} absolute={600+f} title="Prepare, then wait" copy={['Memory data is the pending x5 value.','PC + 4 is also ready for the same edge.']}><RiscBoard><text x={45} y={40} fill={COLORS.textMuted} fontSize={28}>STORED NOW</text><text x={500} y={40} fill={COLORS.accent} fontSize={28}>READY FOR THE EDGE</text><RegisterBank values={[{index:5,value:s.rdValue}]} x={45} y={100} width={320}/><DataTokens tokens={[{label:'Stored PC',value:hex(s.pc),x:45,y:300,width:320},{label:'Pending x5',value:s.pendingData??'—',x:510,y:100,width:340},{label:'Next PC',value:hex(s.nextPc),x:510,y:300,width:340}]}/><text x={45} y={535} fill={COLORS.textStrong} fontSize={29}>Both old values remain stored until the edge.</text></RiscBoard></CyclePage>;}
function Commit({frame:f}:{frame:number}){const s=rv05State(750+f);return <CyclePage f={f} absolute={750+f} title="One edge commits both" copy={['x5 receives the loaded value 42.','PC advances to the following instruction.']}><RiscBoard><RegisterBank values={s.values} writeIndex={s.committed?5:null} x={45} y={100} width={350}/><DataTokens tokens={[{label:'Stored PC',value:hex(s.pc),x:540,y:100,width:320}]}/><path d="M60 385 H420 V320 H835" fill="none" stroke={COLORS.axis} strokeWidth={5}/><circle cx={s.committed?570:390} cy={s.committed?320:385} r={14} fill={s.committed?COLORS.result:COLORS.accent}/><text x={45} y={485} fill={COLORS.result} fontSize={34}>x5 = {s.rdValue}   ·   PC = {hex(s.pc)}</text><text x={45} y={555} fill={COLORS.textMuted} fontSize={26}>Data memory remains unchanged: {s.load} at {hex(T.base+T.offset)}.</text></RiscBoard></CyclePage>;}
export const SCENES:SceneDef[]=[{id:'fetch',Comp:Fetch,dur:150},{id:'readbase',Comp:ReadBase,dur:150},{id:'address',Comp:Address,dur:150},{id:'memory',Comp:Memory,dur:150},{id:'writeback',Comp:Writeback,dur:150},{id:'commit',Comp:Commit,dur:150}];
