import React from 'react';
import {Backdrop} from '../components/Backdrop';
import {Kicker,Heading,Lines,Caption} from '../components/ui';
import {RiscBoard,BitFields,RegisterBank,DataTokens,PipelineLanes,AddressParts,MemoryWords} from '../components/RiscV';
import {COLORS,FONT,fadeIn,ramp} from '../theme';
import type {SceneDef} from '../Video';
import {rv14State} from '../mechanisms/rv14-state';
const T = {"va": 1077948840, "indexBits": 9, "offsetBits": 12, "pteBytes": 8, "leafPPN": 74565};
const DESIGN_AUDIT = {visualArgument: "Colored bit groups become numerical indexes that select actual table rows; returned PPN values become the next base until a readable leaf replaces the VPN.", motion: "Bit slicing, three indexed PTE reads with pending-to-returned PPN data; each PPN travels into its receiver before the next base is filled, followed by offset-preserving concatenation and data read.", example: "VA0x404031A8 selects indexes1/2/3 and maps viaPPN0x12345 toPA0x123451A8.", antiTemplate: "Unlike load/store address addition, this changes address identity through three data-dependent table reads and a preserved offset lane.", sceneRationale: "Six scenes allocate one slice, three dependentPTE reads, one address join and one data read. Combining the middle levels would conceal the data-dependent base handoff;33seconds leaves time to read each hexadecimal result."};
const hex=(n:number|null)=>n===null?'pending':'0x'+n.toString(16).toUpperCase();
const Translation=({frame,t,part,title,copy}:{frame:number;t:number;part:number;title:string;copy:string[]})=>{
 const s=rv14State(t);const active=part>=1&&part<=3?part-1:2;const row=s.walk[active];
 return <div data-root style={{position:'absolute',inset:0,fontFamily:FONT}}><Backdrop width={1920} height={1080}/><Kicker text="RISC-V · SV39 ADDRESS TRANSLATION" frame={frame}/>
 <Heading text={title} frame={frame} width={650} size={50}/><Lines items={copy} frame={frame} start={24} step={12} top={345} width={615} size={30}/>
 <Caption text="RV64 Sv39 · 4 KiB page · S-mode read · valid readable leaf" frame={frame} start={48} top={920} width={1650} size={25}/>
 <div style={{position:'absolute',left:850,top:250,opacity:fadeIn(frame,12)}}><RiscBoard>
 <AddressParts y={65} parts={[{label:'VPN2',bits:9,value:s.vpn[0]},{label:'VPN1',bits:9,value:s.vpn[1]},{label:'VPN0',bits:9,value:s.vpn[2]},{label:'offset',bits:12,value:hex(s.offset)}]}/>
 {part===0&&<g><text x={480} y={235} textAnchor="middle" fontSize={30} fill={COLORS.textStrong}>VA = 0x00000000404031A8</text><text x={480} y={285} textAnchor="middle" fontSize={25} fill={COLORS.textMuted}>38:30 | 29:21 | 20:12 | 11:0</text><DataTokens tokens={s.vpn.map((v,i)=>({label:`9-bit index ${2-i}`,value:v,x:45+i*235,y:370}))}/><DataTokens tokens={[{label:'12-bit offset',value:hex(s.offset),x:745,y:475}]}/></g>}
 {part>=1&&part<=3&&<g><text x={480} y={205} textAnchor="middle" fontSize={28} fill={COLORS.textStrong}>{hex(row.base)} + {row.index} × 8 = {hex(row.address)}</text><MemoryWords x={60} y={250} width={830} rowHeight={78} words={[{address:hex(row.address),value:hex(row.pte)}]} selectedAddress={row.returned?hex(row.address):undefined}/><text x={480} y={360} textAnchor="middle" fontSize={26} fill={row.returned?COLORS.result:COLORS.textMuted}>{!row.returned?'Waiting for PTE read':row.leaf?'V=1  R=1  A=1 → readable leaf':'V=1  R=W=X=0 → pointer returned'}</text><g data-role="ppn-receiver"><rect x={555} y={505} width={345} height={72} rx={12} fill="none" stroke={COLORS.result} strokeWidth={2} strokeDasharray={row.delivered?undefined:'7 5'}/><text x={727.5} y={550} textAnchor="middle" fontSize={28} fill={COLORS.textStrong}>{row.delivered?hex(row.leaf?row.nextPpn:row.nextBase):!row.returned?'pending':''}</text><text x={727.5} y={593} textAnchor="middle" fontSize={22} fill={COLORS.textMuted}>{row.leaf?'Leaf PPN ready':'Next base = PPN << 12'}</text></g>{!row.delivered&&<DataTokens tokens={[{label:row.returned?'':'Returned PPN',value:hex(row.nextPpn),x:row.tokenX,y:row.tokenY,width:345}]}/>}<text x={150} y={555} textAnchor="middle" fontSize={23} fill={COLORS.textMuted}>Offset: {hex(s.offset)}</text></g>}
 {part===4&&<g><DataTokens tokens={[{label:'Leaf PPN',value:hex(s.leafPpn),x:60,y:250,width:240},{label:'Unchanged offset',value:hex(s.offset),x:s.offsetX,y:400}]}/><text x={470} y={300} fill={COLORS.textStrong} fontSize={34}>« 12</text><text x={480} y={365} textAnchor="middle" fill={COLORS.textStrong} fontSize={29}>0x12345000 + 0x1A8</text>{s.pa!==null&&<DataTokens tokens={[{label:'Physical address',value:hex(s.pa),x:60,y:475,width:300}]}/>}</g>}
 {part===5&&<g><MemoryWords x={100} y={255} width={740} selectedAddress={s.pa===null?'':hex(s.pa)} words={[{address:'0x123451A8',value:'0x5A'}]}/><DataTokens tokens={[{label:'Load byte',value:'0x5A',x:180+380*ramp(t,855,45),y:410}]}/><RegisterBank x={575} y={505} width={300} values={[{index:10,value:s.x10===null?'—':hex(s.x10)}]}/><text x={480} y={210} textAnchor="middle" fontSize={27} fill={COLORS.result}>PA = {s.pa===null?'pending':hex(s.pa)}</text></g>}
 </RiscBoard></div></div>;
};
const Slice=({frame}:{frame:number})=><Translation frame={frame} t={frame} part={0} title="Split the virtual address" copy={['Three 9-bit indexes select page entries.','The low 12 bits are the page offset.','Bits 63–39 match sign bit 38.']}/>;
const Root=({frame}:{frame:number})=><Translation frame={frame} t={165+frame} part={1} title="Index the root page table" copy={['satp.PPN = 0x80000 gives the root base.','VPN2 = 1 selects entry 1.','Each Sv39 PTE is 8 bytes.']}/>;
const Middle=({frame}:{frame:number})=><Translation frame={frame} t={330+frame} part={2} title="Follow the first pointer" copy={['The returned PPN forms base 0x80001000.','VPN1 = 2 adds 16 bytes.','Its PPN leads to the final table.']}/>;
const Leaf=({frame}:{frame:number})=><Translation frame={frame} t={480+frame} part={3} title="Stop at the readable leaf" copy={['VPN0 = 3 adds 24 bytes.','R = 1 identifies a leaf entry.','The read returns physical PPN 0x12345.']}/>;
const Join=({frame}:{frame:number})=><Translation frame={frame} t={660+frame} part={4} title="Keep the offset unchanged" copy={['Shift the leaf PPN left by 12 bits.','Copy the original offset 0x1A8.','Physical address: 0x123451A8.']}/>;
const Read=({frame}:{frame:number})=><Translation frame={frame} t={840+frame} part={5} title="Read the translated location" copy={['The load accesses physical memory.','Byte 0x5A returns to x10.','The page changed; its offset did not.']}/>;
export const SCENES:SceneDef[]=[{id:'slice',Comp:Slice,dur:165},{id:'root',Comp:Root,dur:165},{id:'middle',Comp:Middle,dur:150},{id:'leaf',Comp:Leaf,dur:180},{id:'join',Comp:Join,dur:180},{id:'read',Comp:Read,dur:150}];
