import React from 'react';
import {COLORS,FONT,alpha} from '../theme';
export const RiscBoard=({children,width=960,height=600}:{children:React.ReactNode;width?:number;height?:number})=><svg data-k="figure" data-n="RISC-V mechanism" width={width} height={height} viewBox="0 0 960 600" style={{fontFamily:FONT,overflow:'visible'}}>{children}</svg>;
export type Field={label:string;bits:number;value:string|number;color?:string};
export const BitFields=({fields,x=35,y=80,width=890,height=94,progress=1}:{fields:Field[];x?:number;y?:number;width?:number;height?:number;progress?:number})=>{
 const total=fields.reduce((s,f)=>s+f.bits,0);let offset=0;
 return <g opacity={progress}>{fields.map((f,i)=>{const w=width*f.bits/total;const px=x+offset;offset+=w;const color=f.color??[COLORS.primary,COLORS.accent,COLORS.alt,COLORS.result][i%4];return <g key={i}><rect x={px+2} y={y} width={w-4} height={height} rx={7} fill={alpha(color,.14)} stroke={color} strokeWidth={2}/><text x={px+w/2} y={y-15} textAnchor="middle" fill={COLORS.textMuted} fontSize={22}>{f.label}</text><text x={px+w/2} y={y+height/2+9} textAnchor="middle" fill={COLORS.textStrong} fontSize={Math.min(27,w/Math.max(String(f.value).length,1)*1.45)}>{f.value}</text></g>})}</g>;
};
export const RegisterBank=({values,readIndices=[],writeIndex=null,x=40,y=65,width=400,rowHeight=64,progress=1}:{values:{index:number;value:number|string}[];readIndices?:number[];writeIndex?:number|null;x?:number;y?:number;width?:number;rowHeight?:number;progress?:number})=><g opacity={progress}>{values.map((v,i)=>{const col=writeIndex===v.index?COLORS.result:readIndices.includes(v.index)?COLORS.accent:COLORS.primary;return <g key={v.index}><rect x={x} y={y+i*rowHeight} width={width} height={rowHeight-8} rx={8} fill={alpha(col,.12)} stroke={col} strokeWidth={2}/><text x={x+20} y={y+i*rowHeight+36} fill={COLORS.textMuted} fontSize={26}>x{v.index}</text><text x={x+width-22} y={y+i*rowHeight+36} textAnchor="end" fill={COLORS.textStrong} fontSize={30}>{v.value}</text></g>})}</g>;
export const DataTokens=({tokens,progress=1}:{tokens:{label:string;value:string|number;x:number;y:number;color?:string;width?:number}[];progress?:number})=><g opacity={progress}>{tokens.map((t,i)=>{const w=t.width??180;return <g key={i} transform={`translate(${t.x},${t.y})`}><rect width={w} height={72} rx={12} fill={alpha(t.color??COLORS.accent,.16)} stroke={t.color??COLORS.accent} strokeWidth={2}/><text x={w/2} y={-10} fill={COLORS.textMuted} textAnchor="middle" fontSize={22}>{t.label}</text><text x={w/2} y={47} fill={COLORS.textStrong} textAnchor="middle" fontSize={28}>{t.value}</text></g>})}</g>;
export const PipelineLanes=({instructions,x=40,y=90,stageWidth=172,rowHeight=76,progress=1}:{instructions:{id:string;label:string;stage:number;row?:number;killed?:boolean;value?:string|number}[];x?:number;y?:number;stageWidth?:number;rowHeight?:number;progress?:number})=><g opacity={progress}>{['IF','ID','EX','MEM','WB'].map((s,i)=><g key={s}><rect x={x+i*stageWidth} y={y} width={stageWidth-8} height={400} fill={alpha(COLORS.primary,.035)} stroke={COLORS.axis}/><text x={x+i*stageWidth+(stageWidth-8)/2} y={y-22} textAnchor="middle" fontSize={27} fill={COLORS.textMuted}>{s}</text></g>)}{instructions.filter(t=>t.stage>=0&&t.stage<=4).map((t,i)=><g key={t.id} transform={`translate(${x+t.stage*stageWidth+5},${y+30+(t.row??i)*rowHeight})`} opacity={t.killed?.25:1}><rect width={stageWidth-18} height={60} rx={8} fill={alpha(t.killed?COLORS.warn:COLORS.accent,.2)} stroke={t.killed?COLORS.warn:COLORS.accent} strokeWidth={2}/><text x={(stageWidth-18)/2} y={25} textAnchor="middle" fill={COLORS.textStrong} fontSize={21}>{t.label}</text><text x={(stageWidth-18)/2} y={49} textAnchor="middle" fill={COLORS.result} fontSize={22}>{t.value??''}</text>{t.killed&&<path d={`M5 5 L${stageWidth-23} 55 M5 55 L${stageWidth-23} 5`} stroke={COLORS.warn} strokeWidth={4}/>}</g>)}</g>;
export const AddressParts=({parts,x=35,y=70,width=890,progress=1}:{parts:Field[];x?:number;y?:number;width?:number;progress?:number})=><BitFields fields={parts} x={x} y={y} width={width} height={90} progress={progress}/>;
export const MemoryWords=({words,selectedAddress,x=470,y=85,width=430,rowHeight=70,progress=1}:{words:{address:string|number;value:string|number}[];selectedAddress?:string|number;x?:number;y?:number;width?:number;rowHeight?:number;progress?:number})=><g opacity={progress}>{words.map((v,i)=>{const c=v.address===selectedAddress?COLORS.result:COLORS.primary;return <g key={String(v.address)}><rect x={x} y={y+i*rowHeight} width={width} height={rowHeight-8} rx={5} fill={alpha(c,.12)} stroke={c} strokeWidth={2}/><text x={x+14} y={y+i*rowHeight+39} fill={COLORS.textMuted} fontSize={23}>{v.address}</text><text x={x+width-17} y={y+i*rowHeight+39} fill={COLORS.textStrong} fontSize={28} textAnchor="end">{v.value}</text></g>})}</g>;
