import React from 'react';
import {COLORS,FONT} from '../theme';
import {MarketDiagram,UtilityPlane} from './Market';
const FIT: Record<string,{dx:number;dy:number;scale:number}> = {"mi01-supply-and-demand-balance": {"dx": 13, "dy": 100, "scale": 0.67}, "mi02-relatively-static": {"dx": 13, "dy": 100, "scale": 0.67}, "mi03-elasticity-of-demand": {"dx": 13, "dy": 100, "scale": 0.67}, "mi04-tax-burden-incidence": {"dx": 13, "dy": 100, "scale": 0.67}, "mi05-deadweight-loss": {"dx": 13, "dy": 100, "scale": 0.67}, "mi06-maximize-consumer-utility": {"dx": 13, "dy": 100, "scale": 0.67}, "mi07-cost-curve": {"dx": 13, "dy": 100, "scale": 0.67}, "mi08-manufacturers-output-decisions": {"dx": 13, "dy": 100, "scale": 0.67}, "mi09-perfect-competition": {"dx": 13, "dy": 100, "scale": 0.67}, "mi10-monopoly-pricing": {"dx": 13, "dy": 100, "scale": 0.67}, "mi11-market-welfare": {"dx": 13, "dy": 100, "scale": 0.67}};
import {stateAt as state0} from '../videos/mi01-supply-and-demand-balance.state';
const Figure0:React.FC = ()=>{const f=899;const st=state0(f);const fit=FIT['mi01-supply-and-demand-balance'];return <div style={{width:640,height:620}}><div style={{width:950,height:620,transform:`translate(${fit.dx}px,${fit.dy}px) scale(${fit.scale})`,transformOrigin:'0 0'}}><MarketDiagram curves={[{name:'D',fn:q=>12-q,color:COLORS.primary},{name:'S',fn:q=>2+q,color:COLORS.alt}]} marks={[{q:st.qd,p:st.p,label:`Demand ${st.qd.toFixed(1)}`,color:COLORS.accent},{q:st.qs,p:st.p,label:`Supply ${st.qs.toFixed(1)}`,color:COLORS.alt}]} areas={[{points:[[st.qd,st.p-.16],[st.qs,st.p-.16],[st.qs,st.p+.16],[st.qd,st.p+.16]],color:COLORS.warn}]} footer={`Price ${st.p.toFixed(1)} · ${st.qs>st.qd?'surplus':st.qd>st.qs?'shortage':'balanced'} ${st.gap.toFixed(1)}`}/></div></div>;};
import {stateAt as state1} from '../videos/mi02-relatively-static.state';
const Figure1:React.FC = ()=>{const f=899;const st=state1(f);const fit=FIT['mi02-relatively-static'];return <div style={{width:640,height:620}}><div style={{width:950,height:620,transform:`translate(${fit.dx}px,${fit.dy}px) scale(${fit.scale})`,transformOrigin:'0 0'}}><MarketDiagram curves={[{name:'D₀',fn:q=>12-q,color:COLORS.primary,dashed:true},{name:'D₁',fn:q=>12+st.shift-q,color:COLORS.accent},{name:'S',fn:q=>2+q,color:COLORS.alt}]} marks={[{q:5,p:7,label:'Old E',color:COLORS.textDim},{q:st.q,p:st.p,label:'New E'}]} footer={`Demand shift +${st.shift.toFixed(1)} · Q* ${st.q.toFixed(1)} · P* ${st.p.toFixed(1)}`}/></div></div>;};
import {stateAt as state2} from '../videos/mi03-elasticity-of-demand.state';
const Figure2:React.FC = ()=>{const f=899;const st=state2(f);const fit=FIT['mi03-elasticity-of-demand'];return <div style={{width:640,height:620}}><div style={{width:950,height:620,transform:`translate(${fit.dx}px,${fit.dy}px) scale(${fit.scale})`,transformOrigin:'0 0'}}><MarketDiagram curves={[{name:'Elastic D',fn:q=>(18-q)/2,color:COLORS.accent},{name:'Inelastic D',fn:q=>18-2*q,color:COLORS.alt}]} marks={[{q:st.qe,p:st.p,label:'Elastic',color:COLORS.accent},{q:st.qi,p:st.p,label:'Inelastic',color:COLORS.alt}]} areas={[{points:[[0,0],[st.qe,0],[st.qe,st.p],[0,st.p]],color:COLORS.accent},{points:[[0,0],[st.qi,0],[st.qi,st.p],[0,st.p]],color:COLORS.alt}]} footer={`P ${st.p.toFixed(1)} · elastic R ${st.re.toFixed(1)} · inelastic R ${st.ri.toFixed(1)}`} yMax={20}/></div></div>;};
import {stateAt as state3} from '../videos/mi04-tax-burden-incidence.state';
const Figure3:React.FC = ()=>{const f=899;const st=state3(f);const fit=FIT['mi04-tax-burden-incidence'];return <div style={{width:640,height:620}}><div style={{width:950,height:620,transform:`translate(${fit.dx}px,${fit.dy}px) scale(${fit.scale})`,transformOrigin:'0 0'}}><MarketDiagram curves={[{name:'D',fn:q=>12-q,color:COLORS.primary},{name:'S',fn:q=>2+q,color:COLORS.alt},{name:'S + tax',fn:q=>2+q+st.tax,color:COLORS.accent}]} marks={[{q:st.q,p:st.pc,label:'Buyer price',color:COLORS.accent},{q:st.q,p:st.pp,label:'Seller price',color:COLORS.alt}]} areas={[{points:[[0,st.pp],[st.q,st.pp],[st.q,st.pc],[0,st.pc]],color:COLORS.result}]} footer={`Tax ${st.tax.toFixed(1)} · buyers +${st.consumer.toFixed(1)} · sellers −${st.producer.toFixed(1)}`}/></div></div>;};
import {stateAt as state4} from '../videos/mi05-deadweight-loss.state';
const Figure4:React.FC = ()=>{const f=899;const st=state4(f);const fit=FIT['mi05-deadweight-loss'];return <div style={{width:640,height:620}}><div style={{width:950,height:620,transform:`translate(${fit.dx}px,${fit.dy}px) scale(${fit.scale})`,transformOrigin:'0 0'}}><MarketDiagram curves={[{name:'MB',fn:q=>12-q,color:COLORS.primary},{name:'MC',fn:q=>2+q,color:COLORS.alt}]} marks={[{q:st.q,p:st.mb,label:'Excluded benefit',color:COLORS.accent},{q:st.q,p:st.mc,label:'Excluded cost',color:COLORS.alt}]} areas={[{points:[[st.q,st.mc],[5,7],[st.q,st.mb]],color:COLORS.warn}]} footer={`Trade limit Q ${st.q.toFixed(1)} · lost gains = ${st.loss.toFixed(2)}`}/></div></div>;};
import {stateAt as state5} from '../videos/mi06-maximize-consumer-utility.state';
const Figure5:React.FC = ()=>{const f=899;const st=state5(f);const fit=FIT['mi06-maximize-consumer-utility'];return <div style={{width:640,height:620}}><div style={{width:950,height:620,transform:`translate(${fit.dx}px,${fit.dy}px) scale(${fit.scale})`,transformOrigin:'0 0'}}><UtilityPlane x={st.x} budget={10}/></div></div>;};
import {stateAt as state6} from '../videos/mi07-cost-curve.state';
const Figure6:React.FC = ()=>{const f=540;const st=state6(f);const fit=FIT['mi07-cost-curve'];return <div style={{width:640,height:620}}><div style={{width:950,height:620,transform:`translate(${fit.dx}px,${fit.dy}px) scale(${fit.scale})`,transformOrigin:'0 0'}}><MarketDiagram curves={[{name:'MC',fn:q=>2+2*q,color:COLORS.accent},{name:'ATC',fn:q=>16/Math.max(.2,q)+2+q,color:COLORS.alt},{name:'AVC',fn:q=>2+q,color:COLORS.primary}]} marks={[{q:st.q,p:st.atc,label:'Current ATC',color:COLORS.alt},{q:4,p:10,label:'Minimum ATC'}]} footer={`Q ${st.q.toFixed(1)} · AFC ${st.afc.toFixed(1)} · MC ${st.mc.toFixed(1)}`} xMax={8} yMax={24}/></div></div>;};
import {stateAt as state7} from '../videos/mi08-manufacturers-output-decisions.state';
const Figure7:React.FC = ()=>{const f=899;const st=state7(f);const fit=FIT['mi08-manufacturers-output-decisions'];return <div style={{width:640,height:620}}><div style={{width:950,height:620,transform:`translate(${fit.dx}px,${fit.dy}px) scale(${fit.scale})`,transformOrigin:'0 0'}}><svg data-k="figure" width={950} height={620} viewBox="0 0 950 620" style={{fontFamily:FONT}}>
 <text x={90} y={60} fontSize={28} fill={COLORS.textStrong}>Output Q = {st.q} · price = {st.mr.toFixed(0)}</text>
 <line x1={90} x2={850} y1={335} y2={335} stroke={COLORS.axis}/>
 <rect x={150} y={335-st.tr*2.1} width={200} height={st.tr*2.1} fill={COLORS.accent}/><rect x={450} y={335-st.tc*2.1} width={200} height={st.tc*2.1} fill={COLORS.alt}/>
 <text x={150} y={375} fontSize={27} fill={COLORS.accent}>Revenue {st.tr.toFixed(0)}</text><text x={450} y={375} fontSize={27} fill={COLORS.alt}>Cost {st.tc.toFixed(0)}</text>
 <text x={90} y={440} fontSize={34} fill={st.profit>=0?COLORS.result:COLORS.warn}>Profit = {st.profit.toFixed(0)}</text>
 {Array.from({length:8},(_,q)=><g key={q}><circle cx={150+q*85} cy={535-(10*q-q*q-8)*3} r={q===st.q?12:6} fill={q===st.q?COLORS.result:COLORS.textDim}/><text x={150+q*85} y={607} fontSize={22} textAnchor="middle" fill={COLORS.textDim}>{q}</text></g>)}
 <text x={670} y={110} fontSize={27} fill={COLORS.textStrong}>MR {st.mr.toFixed(0)}</text><text x={670} y={155} fontSize={27} fill={COLORS.textStrong}>MC {st.mc.toFixed(0)}</text>
 </svg></div></div>;};
import {stateAt as state8} from '../videos/mi09-perfect-competition.state';
const Figure8:React.FC = ()=>{const f=899;const st=state8(f);const fit=FIT['mi09-perfect-competition'];return <div style={{width:640,height:620}}><div style={{width:950,height:620,transform:`translate(${fit.dx}px,${fit.dy}px) scale(${fit.scale})`,transformOrigin:'0 0'}}><MarketDiagram curves={[{name:'Demand',fn:q=>26-q,color:COLORS.primary},{name:'S before',fn:q=>2+q,color:COLORS.alt,dashed:true},{name:'S after',fn:q=>2+q-st.entry,color:COLORS.accent}]} marks={[{q:st.marketQ,p:st.p,label:'Market E'}]} xMax={22} yMax={28} footer={`Market P ${st.p.toFixed(1)} · firm q ${st.q.toFixed(1)} · profit ${st.profit.toFixed(1)}`}/></div></div>;};
import {stateAt as state9} from '../videos/mi10-monopoly-pricing.state';
const Figure9:React.FC = ()=>{const f=899;const st=state9(f);const fit=FIT['mi10-monopoly-pricing'];return <div style={{width:640,height:620}}><div style={{width:950,height:620,transform:`translate(${fit.dx}px,${fit.dy}px) scale(${fit.scale})`,transformOrigin:'0 0'}}><MarketDiagram curves={[{name:'Demand',fn:q=>14-q,color:COLORS.primary},{name:'MR',fn:q=>14-2*q,color:COLORS.accent},{name:'MC',fn:q=>2+q,color:COLORS.alt}]} marks={[{q:st.q,p:st.readPrice,label:f<450?'Choose Q':f<630?'Read upward':'Monopoly price',color:COLORS.accent},{q:6,p:8,label:'Competition',color:COLORS.result}]} areas={f>=630?[{points:[[4,6],[6,8],[4,10]],color:COLORS.warn}]:[]} footer={`Q ${st.q.toFixed(1)} · MR ${st.mr.toFixed(1)} · P ${st.price.toFixed(1)} · DWL ${f>=630?st.dwl.toFixed(0):'—'}`}/></div></div>;};
import {stateAt as state10} from '../videos/mi11-market-welfare.state';
const Figure10:React.FC = ()=>{const f=899;const st=state10(f);const fit=FIT['mi11-market-welfare'];return <div style={{width:640,height:620}}><div style={{width:950,height:620,transform:`translate(${fit.dx}px,${fit.dy}px) scale(${fit.scale})`,transformOrigin:'0 0'}}><MarketDiagram curves={[{name:'MB',fn:q=>12-q,color:COLORS.primary},{name:'MC',fn:q=>2+q,color:COLORS.alt}]} marks={[{q:st.q,p:st.mb,label:'Next benefit',color:COLORS.accent}]} areas={[{points:[[0,7],[st.q,7],[st.q,12-st.q],[0,12]],color:COLORS.primary},{points:[[0,2],[st.q,2+st.q],[st.q,7],[0,7]],color:COLORS.alt}]} footer={`Q ${st.q.toFixed(1)} · CS ${st.cs.toFixed(1)} + PS ${st.ps.toFixed(1)} = ${st.total.toFixed(1)}`}/></div></div>;};
export const COVER_FIGURES:Record<string,React.FC> = {'mi01-supply-and-demand-balance':Figure0,'mi02-relatively-static':Figure1,'mi03-elasticity-of-demand':Figure2,'mi04-tax-burden-incidence':Figure3,'mi05-deadweight-loss':Figure4,'mi06-maximize-consumer-utility':Figure5,'mi07-cost-curve':Figure6,'mi08-manufacturers-output-decisions':Figure7,'mi09-perfect-competition':Figure8,'mi10-monopoly-pricing':Figure9,'mi11-market-welfare':Figure10};